// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wakjiiznvyuebfmnklmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indha2ppaXpudnl1ZWJmbW5rbG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDMzMjcsImV4cCI6MjA3MDYxOTMyN30.nyb-Y11sFW2eGA9rKkMW60-P-w4SllsmGAPZmL_EkO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});